### ISSUE TITLE
"pull together data on deadline filers"

### ISSUE THREAD

**Issue by jeremyjbowers** [jsfenfen/paper_fec#5]
I don't know what this means, but it's listed as a next step.

**Comment by jsfenfen** [comment]
I've got a dump of the timestamps, down to the minute, anyway, of filings received on the busiest days of 2014 in FEC land. 2016 traffic will be bigger than 2014, of course, but...

**Comment by jsfenfen** [comment]
Here's a sample file of 10/15/14, for example: https://github.com/jsfenfen/paper_fec/blob/c64ad7afe013d9f695bfb05a780e2875abf84a00/helpers/2014-10-15.csv

closed in c64ad7afe013d9f695bfb05a780e2875abf84a00
