### ISSUE TITLE
Remove dependency on local_FEC_settings.py

### ISSUE THREAD

**Issue by jeremyjbowers** [jsfenfen/paper_fec#6]
Factor these out into env vars OR better, make some assumptions and make them overridable.

**Comment by jeremyjbowers** [comment]
Most of this is storage for temp files, which we're going to refactor into a document store (I think), so we can talk about this?

**Comment by jsfenfen** [comment]
closed for now in 7a13ebc9b7767114c20203719e1db20c14ba410e by pushing all to settings file.
